// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function CreateDirectory(arg1:string):Promise<void>;

export function CreateFile(arg1:string):Promise<void>;

export function Delete(arg1:string):Promise<void>;

export function GetDirectoryLevel(arg1:string):Promise<Array<main.FileNode>>;

export function GetInitialFile():Promise<main.InitialFile>;

export function GetSettings(arg1:string):Promise<main.Settings>;

export function Greet(arg1:string):Promise<string>;

export function OpenWorkspaceDialog():Promise<string>;

export function PrintToPDF(arg1:string,arg2:string):Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function Rename(arg1:string,arg2:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:main.Settings,arg2:string):Promise<void>;

export function ToggleDiscordRPC(arg1:boolean):Promise<void>;
